README.md, lib/signet/signer.ex, lib/signet/test/signer.ex, mix.exs
Since race conditions on setup of the credentials processes are tough, we change to fetch address from the credentials server lazily.
=> find and memoize address on call rather than init

CHANGELOG.md, README.md, lib/signet/rpc.ex, mix.exs, test/lib/client.ex
This patch starts to add support to building a transaction based on base fee and priority fee. These are the first changes to start to make Signet compliant with EIP-1559, but we still currently add the fees together and wrap them in a Legacy transaction. This will more or less give the same functionality as users should specify `priority_fee` and let the base fee be handled by the protocol.
Note: this isn't great since we add a 20% buffer to the base fee that _becomes_ a priority fee. We'll fix this in future upgrades.
=> Add Base Fee & Priority Fee Support

CHANGELOG.md, README.md, lib/signet/recover.ex, mix.exs
According to [EIP-155](https://eips.ethereum.org/EIPS/eip-155), signatures for Ethereum transactions or messages use a recovery bit that is `35 + chain_id * 2 + rec_id`, which we took to mean an odd recovery bit would mean the original rec_id was 0, and an even would mean the original rec_id was 1. But when hardware wallets and other people sign and don't follow EIP-155, then 0 should still imply a rec_id of 0, and 1 should still imply a rec_id of 1, and thus we add explicit support for that in this patch.
=> Handle Non-EIP-155 Signatures

CHANGELOG.md, README.md, lib/signet/util.ex, mix.exs, test/util_test.exs
This patch adds a bunch of minor functions to help with EIP-155-type signatures. Ethereum has multiple ways of passing through a recovery bit. Either 0,1, or 27,28, or `35+chain_id*2+{0,1}`. We make it seamless to convert between these for signatures.
=> Add EIP-155 Signature Helpers

.github/CODEOWNERS, .github/workflows/publish.yml, CHANGELOG.md, README.md, mix.exs
This patch adds the ability to auto-public to Hex when a new release is created. This should simplify the flow for pushing new versions.
=> Add Publish from Releases

README.md, lib/signet/receipt.ex, lib/signet/rpc.ex, mix.exs, test/receipt_test.exs, test/support/client.ex
This patch adds a new RPC endpoint `Signet.RPC.get_trx_receipt/1` which allows users to pull transaction receipts using `eth_getTransactionReceipt` RPC endpoint call.
Bump to 0.2.0-alpha2
=> Add RPC for Get Transaction Receipt

README.md, lib/signet/rpc.ex, lib/signet/trace.ex, lib/signet/typed.ex, mix.exs, test/support/client.ex, test/trace_test.exs
This patch adds basic support for the `trace_transaction` RPC call. See https://docs.infura.io/networks/ethereum/json-rpc-methods/trace-methods/trace_transaction for more information on the endpoint details.
Bump to 0.2.0-alpha3
=> Add `trace_transaction` Support

README.md, mix.exs, mix.lock
This patch simply updates the `abi` dependency.
Bump to 1.0.0-alpha3
=> Bump ABI Dep

README.md, lib/signet/rpc.ex, mix.exs
This patch accepts `chain_id` as an input option to `prepare_trx` instead of using the default chain_id for the signer. This is as we move to a better version of multi-chain world.
Bump to 1.0.0-alpha4
=> Allow Setting Chain ID in Prepare Trx

README.md, lib/signet/rpc.ex, mix.exs, test/support/client.ex
This patch adds [trace_call](https://docs.alchemy.com/reference/trace-call) support, used to speculatively trace calls before being submitted.
Bump to 1.0.0-alpha5
=> Add `trace_call` Support (1.0.0-alpha5)

CHANGELOG.md, README.md, lib/signet/rpc.ex, mix.exs
Previously we had `send_rpc` return a tuple of the form `{:error, String.t()}`, which has problematic since in many cases that data was less useful than the error returned from the JSON-RPC node (e.g. the error code got put into that string). Here, we fix this by making this call always return `{:error, %{code: code, message: message}}`, which is easier for clients to parse. Additionally parsed information, such as `%{code: 3, message: "execution reverted", revert: <<1,2,3>>, error_abi: "Cool()", error_params: []}` can expand this struct, but it will always have code and message on it. This should be a boon for callers. Note: this is a breaking change and could break earlier clients.
Bump to 1.0.0-alpha6
=> Adjust RPC Call Return Value (1.0.0-alpha6)

README.md, lib/signet/fee_history.ex, lib/signet/rpc.ex, lib/signet/trace.ex, mix.exs, test/fee_history_test.exs, test/support/client.ex
This patch adds fee history and max fee per gas RPC endpoints and incorporates them when deciding EIP-1559 transaction gas.
=> Add Fee History and MaxFeePerGas Endpoints [1.0.0-alpha8]

CHANGELOG.md, README.md, lib/signet/fee_history.ex, lib/signet/rpc.ex, mix.exs
Rewards may be nil from `eth_feeHistory`, this patch properly decodes that allowing for nils.
=> Allow nil `rewards` from eth_feeHistory [1.0.0-alpha10]

README.md, lib/signet/typed.ex, mix.exs
This patch adds `list` as a viable type for an EIP-712 typed data array.
Bump to 1.0.0-beta1
=> Add Lists to EIP-712 Implementation

README.md, lib/signet/typed.ex, lib/signet/util.ex, mix.exs
This patch adds a few extra network chains, e.g. `sepolia` and `base_sepolia`.
Also we run `mix format`.
Bump to 1.0.0-beta2
=> Add a few extra network chains

README.md, lib/signet/transaction.ex, mix.exs
Due to EIP-155, some signatures come in wide (e.g. with a very large recovery "bit"), this is esp. true for nets like Sepolia with chain_id=11155111. Signatures should be passed in in a nice parsed way (r, s, and v), but if they are binary-packed, then EIP-155 means that large nets will overflow 1-byte (originally allocated for `v`). Here, we expand the signature to allow wider-`v`s.
Bump to 1.0.0-beta3
=> Allow Wide V2 Signatures

README.md, lib/signet/rpc.ex, mix.exs
This patch simply allows the caller to specify the id to the `send_rpc` call.
Bump to 1.0.0-beta4
=> Accept `id` to `send_rpc`

CHANGELOG.md, README.md, lib/signet/rpc.ex, mix.exs, test/support/client.ex
This patch fixes a bug where RPC calls would crash if they received errors from the remote node.
=> zImprove RPC Error Handling 1.0.0-beta7

CHANGELOG.md, README.md, lib/mix/signet.gen.ex, mix.exs
Previously we weren't escaping the function selector, that led to concerns with certain expansions. Here we properly escape.
See https://hexdocs.pm/elixir/Macro.html#escape/1
Bump to 1.0.0-charlie2
=> Add Escape to Macro Expands

lib/mix/signet.gen.ex, test/support/signet/contract/block_number.ex, test/support/signet/contract/ierc20.ex
This patch fixes ABI-only generators, e.g. when you _just_ have the ABI, and not the full Solidity output. This allows you to create stub contracts useful for calling, but that don't have "bytecode" or "constructor." Previously we _mostly_ had this working, except the constructor was still being created which was then causing a compilation error since it referenced `bytecode/0` that wasn't being defined.
Additionally, we have a lot of work to do on name overlaps. E.g. in this case there were two functions "abc()" and "ABC()" which Solidity treats as different but end up the same name in our generated code. We fix that, but honestly, we need a bigger system for checking for dups that goes deeper than this patch does.
=> Fix ABI-only Encoding

lib/signet/rpc.ex
This patch fixes call params. For reasons that I don't understand, sometimes we need to use short hex (e.g `0x5` to represent 0x05), but apparently for the `data` parameter, you need to pass in byte-aligned hex. So we fix that since we were getting errors from Anvil (maybe Anvil is weird here?).
Also, we make `to_call_params/2` public since other functions can use it, but we currently don't document it specifically.
=> Fix Call Params

CHANGELOG.md, README.md, lib/signet/sleuth.ex, mix.exs, test/sleuth_test.exs
This patch adds annotations to Sleuth, which includes the types of values so the downstream service can encode certain values how it pleases.
Bump to 1.0.0-charlie5
=> Add Sleuth Annotations

CHANGELOG.md, README.md, lib/signet/typed.ex, mix.exs, test/typed_test.exs
The EIP-712 spec allows for EIP-712 domains which include a _subset_ of the expected keys (`chainId`, `name`, `version`, `verifyingContract` and `salt`). This patch patches our Signet code s.t. we properly allow for domain sub-sets.
Bump to 1.0.0-charlie6
=> Partial EIP-712 Domains

CHANGELOG.md, README.md, lib/mix/signet.gen.ex, lib/signet/filter.ex, mix.exs, mix.lock, test/ierc20_test.exs, test/support/signet/contract/block_number.ex, test/support/signet/contract/ierc20.ex
This patch improves Event Decoders to return error tuples and more reasonably handle the event signature (topic0). This creates a small breaking change in Signet, but nothing too serious. E.g. `Contract.IErc20.decode_transfer_ddf252ad_event` now returns a tuple instead of a raw decode. This is a reasonable and good change.
Bump to 1.0.0-charlie7
=> Bump ABI for Event Decoders

CHANGELOG.md, README.md, config/test.exs, lib/signet/open_chain.ex, mix.exs, test/open_chain_test.exs
This patch begins to add the [OpenChain API](https://docs.openchain.xyz) which allows us to decode errors from a remote database. This should give us extra benefits when trying to decode unknown errors. We can later integrate this OpenChain API into more Signet systems.
=> Add OpenChain API

CHANGELOG.md, README.md, config/test.exs, lib/signet/open_chain.ex, mix.exs, test/open_chain_test.exs
This patch adds a configurable base URL for OpenChain API.
Bump to delta2
=> Add OpenChain Base URL

CHANGELOG.md, README.md, lib/signet/open_chain.ex, mix.exs, test/open_chain_test.exs
This patch simply fixes the OpenChain API Parameters, per the spec https://docs.openchain.xyz/#/default/get_signature_database_v1_lookup. Note: it's event= and function=, despite being lists
=> Fix OpenChain API Parameters

CHANGELOG.md, README.md, lib/signet/filter.ex, mix.exs
This patch adds the ability to filter without an address (e.g. on all addresses) when creating a Filter in Signet.
bump to delta6
=> Filter No Address

lib/signet/util.ex
encode_hex_short does not exist
=> fix typo on Utils.encode_hex deprecation message

.github/workflows/publish.yml, .github/workflows/test.yml
This patch fixes the GitHub test runner, by just bumping the versions of Elixir and OTP.
=> Fix Test Runner

CHANGELOG.md, README.md, lib/signet/rpc.ex, lib/signet/sleuth.ex, mix.exs, test/sleuth_test.exs, test/support/signet/sleuth_handler.ex
This patch adds the ability to easily trace reverts on `call_trx` calls, e.g. so you can easily see the revert reasons. This simply has the ability to try and trace a call after it reverts (by setting `trace_reverts: true`) and then an error that reverted will include a `trace: Trace{}` field that can be observed.
Bump to delta7
=> Trace Reverts

README.md, lib/signet/open_chain.ex, mix.exs
This patch deals with a umatched function sigs crashing since the api response is e.g. `%{"event" => %{}, "function" => %{"0x8379a000" => nil}}` rather than an intuitive empty map or list.
It also adds a function to decode an error signaturea nd it's argument in one call.
=> safely decode nil results to error tuple, function to return error sig and decoded values

README.md, lib/signet/typed.ex, mix.exs
This patch adds the EIP-712 bool type, which was previously excluded. Bump to echo6
=> Add EIP-712 Bool Type

README.md, lib/signet/assembly.ex, lib/signet/typed.ex, lib/signet/vm.ex, mix.exs, test/vm_test.exs
This patch adds `tstore` support for the EVM-VM and bumps to echo7.
=> Add TStore Support [echo7]

lib/signet/sleuth.ex
pretty much what it says in the title.
=> bugfix: when decode_binaries is false, do not decode sized bytes

lib/mix/signet.gen.ex, lib/signet/vm.ex, test/support/signet/contract/block_number.ex, test/support/signet/contract/ierc20.ex, test/support/signet/contract/rock.ex, test/vm_test.exs
This patch adds the ability to call into FFI "foreign-function interfaces," which are hooks back into the EVM's calling context environment. From the perspective of the EVM/Solidity code, this is the same as calling a standard Ethereum precompile (e.g. these functions: https://www.evm.codes/precompiled), but overall, this means we can allow hooks from EVM-VM code, e.g. to fetch offline price data. This lightly violates the concept of being pure, but overall, it's up to the discretion of the author to add hooks or not into code.
Note: we change the signature of `Signet.VM.exec` and `Signet.VM.exec_call` to use `exec_opts`, which allows FFIs, and thus, we change some of our generated code, as well, to match this new format.
Note: we only allow `STATICCALL` right now, but we could easily add …
=> Add FFI Integration

lib/signet/debug_trace.ex, lib/signet/rpc.ex, test/debug_trace_test.exs, test/sleuth_test.exs, test/support/client.ex
This patch adds native support for `debug_traceCall`, which is a different tracing method available on certain nodes (e.g. anvil, QuickNode). This method is more verbose giving actual opcode executions (as opposed to a simple call stack from `trace_call`), but is useful in a variety of contexts (e.g. debugging).
QuickNode docs: https://www.quicknode.com/docs/ethereum/debug_traceCall
=> Support `debug_traceCall`

README.md, lib/signet/rpc.ex, mix.exs, test/vm_test.exs
This patch fixes our `to_call_params` function to send the `"gas"` parameter, based on the `gas_limit` value in the transaction. We previously only sent the gas limit with transactions.
We also fix a small typo in a vm test.
See: https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_call
=> Send Gas Limit [v1.2.1]

README.md, lib/signet/vm.ex, mix.exs, test/vm_test.exs
We previously used `floor(a/b)` for integer math, but this ends up using floating point math and can lead to rounding issues. We replace this with `Integer.floor_div/2`, which fixes the issue as elucidated in the VM test. This caused issues on checking Solidity overflow math.
See also: https://hexdocs.pm/elixir/Integer.html#floor_div/2
=> Fix VM div/sdiv [Bump to 1.2.3]

README.md, lib/signet/assembly.ex, lib/signet/debug_trace.ex, lib/signet/rpc.ex, lib/signet/vm.ex, mix.exs, test/support/client.ex
This patch adds a variety of logging and debugging updates to make the system a bit more manageable when debugging operations, adding trace_reverts to trx preparation and verbose options to the EVM-VM.
Bump to 1.2.6
=> Debugging Updates

README.md, lib/signet/rpc.ex, mix.exs, test/support/client.ex
`trace_call` was erroneously decoding its response as a `Signet.Trace` instead of a `Signet.TraceCall`, which are totally different things (go figure!). We fix this and bump to 1.2.7.
=> Fix trace_call

CHANGELOG.md, README.md, lib/signet/debug_trace.ex, lib/signet/trace.ex, lib/signet/trace_call.ex, lib/signet/util.ex, mix.exs
This patch adds the opposite of `trace.deserialize()` which allows us to re-serialize a JSON (be it a call trace, a trace trx or a debug trace). These are useful for generally printing or showing traces, which can be difficult due to the amount of Elixir-binaries that usually show up.
=> Add Trace Serializers

README.md, lib/signet/rpc.ex, mix.exs, test/support/client.ex
This patch warns for invalid JSON-RPC requests. These requests can be very hard to debug since it's often unclear what the invalid request was, so we log such requests for the user.
Bump to 1.2.9
=> Warn on Invalid RPC Request

lib/signet/sleuth.ex, test/sleuth_test.exs
so, some things happened.
1. i realized that ABI.decode(...) takes a decode_structs opt that
decodes function selector return values into nice atom-keyed maps!
2. i wanted it, because it would let me delete some annoying kludge code
in legend-api. recall an earlier PR where i modified the encoder to
allow string keys? same problem, but now better solution, because the
client can just decode_structs and then they can use encode_query()
like normal, instead of manually ABI.encode(...)ing and not
benefiting from the codegen.
3. i realized that the way Signet.Sleuth decodes named returns and
multiple function returns is... really weird. so i added a
"be_obvious" codepath that doesn't do all that. i never want to see
"var0" and "var1" again.
4. i made it so that using decode_structs …
=> feat: `Signet.Sleuth.query_v2` with more-obvious return types, supporting `:decode_structs` from `abi.ex` for better decoding

README.md, lib/signet/application.ex, lib/signet/open_chain.ex, lib/signet/rpc.ex, mix.exs, test/open_chain_test.exs, test/support/client.ex
bugfix for 1.3.1, which did not pass the finch name to calling of Finch.request
=> use finch request correctly

README.md, lib/signet/filter.ex, lib/signet/rpc.ex, mix.exs
This patch adds `:trace_opts` for `trace_reverts`, which autoatically runs a trace on failed calls. These new opts allow for traces to use different opts, such as a different `ethereum_node`, since only certain node providers allow for traces.
=> Add Trace Opts, Bump to 1.3.8

README.md, lib/signet/util.ex, mix.exs
This patch adds several chains to the chain id configuration.
avalanche,
bnb_smart_chain,
hyperevm,
lens,
polygon,
sonic,
ink,
plume
=> add a few chain ids
